debug: true
build:
  image: 'node:6-alpine'
  environment:
    - NPM_PRIVATE_TOKEN=$$NPM_PRIVATE_TOKEN
    - NPM_NPMJS_TOKEN=$$NPM_NPMJS_TOKEN
  commands:
    - "./.docker/build-drone.sh"
    - "npm run build"
    - "npm prune --production"

cache:
  mount:
    - node_modules
    - .git

publish:
  docker:
    image: leankit/drone-docker
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: leankit/mobile-mobot
    storage_driver: overlay

# deploy:
#   kubernetes:
#     image: quay.io/honestbee/drone-kubernetes
#     kubernetes_server: $$KUBERNETES_SERVER
#     kubernetes_cert: $$KUBERNETES_CERT
#     kubernetes_token: $$KUBERNETES_TOKEN
#     deployment: mobot
#     repo: leankit/mobile-mobot
#     container: mobot
#     tag: latest
#     when:
#         branch: [ master ]

notify:
  slack:
    webhook_url: $$SLACK_WEBHOOK
    username: Azure Drone
    channel: "#pd-builds"
